meta_product_name: "Refective"
meta_title: "Refective - Repair your stuff, help the environment and your wallet"
meta_description: "Refective helps you repair your stuff by connecting you to nearby repair spaces and communities."
meta_image: "cover.png" # should exist in `app/assets/images/`
